import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {ROOT,catalog,readJson,write,writeJson,toUnified,FORMATS} from './common.mjs';
const rows=await catalog(),pkg=await readJson('package.json'),upstream=await readJson('data/emoji-data.upstream.json');
const site=new Map((await readJson('data/site-metadata.json')).map(e=>[e.rgi,e]));
const withoutVS=s=>s.toUpperCase().split('-').filter(x=>x!=='FE0F').join('-');
const byCode=new Map();
for(const parent of upstream){byCode.set(withoutVS(parent.unified),{parent,entry:parent});for(const entry of Object.values(parent.skin_variations||{}))byCode.set(withoutVS(entry.unified),{parent,entry});}
const emojis=rows.map((r,i)=>{
 const unified=toUnified(r.rgi),s=site.get(r.rgi)||{},match=byCode.get(withoutVS(unified));
 const slug=r.name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
 const shortNames=[...new Set([...(match?.parent.short_names||[]),slug])];
 return {emoji:r.emoji,rgi:r.rgi,unified,name:r.name,cldr_name:s.cldrName||r.name,category:r.category,subcategory:s.subgroup||match?.parent.subcategory||'',short_name:shortNames[0],short_names:shortNames,image:unified.toLowerCase()+'.png',sort_order:s.unicodeOrder??i,skin_tones:unified.split('-').filter(x=>/^1F3F[B-F]$/.test(x)),source_sha256:r.sha256};
}).sort((a,b)=>a.sort_order-b.sort_order||a.unified.localeCompare(b.unified));
const known=new Map(emojis.map(e=>[withoutVS(e.unified),e]));const covered=new Set();
const datasource=[];
const project=e=>({name:e.cldr_name.toUpperCase(),unified:e.unified,non_qualified:withoutVS(e.unified)===e.unified?null:withoutVS(e.unified),image:e.image,short_name:e.short_name,short_names:e.short_names,category:e.category,subcategory:e.subcategory,sort_order:e.sort_order,has_img_noto3d:true});
for(const parent of upstream){
 const main=known.get(withoutVS(parent.unified));if(!main)continue;
 const entry={...project(main),added_in:parent.added_in};covered.add(main.unified);
 const variations={};for(const [tones,v] of Object.entries(parent.skin_variations||{})){
  const matched=known.get(withoutVS(v.unified));if(matched){variations[tones]={unified:matched.unified,image:matched.image,has_img_noto3d:true};covered.add(matched.unified);}
 }
 if(Object.keys(variations).length)entry.skin_variations=variations;
 datasource.push(entry);
}
for(const e of emojis)if(!covered.has(e.unified)){datasource.push(project(e));covered.add(e.unified);}
datasource.sort((a,b)=>a.sort_order-b.sort_order);
await writeJson('emoji.json',emojis);await writeJson('emoji-datasource.json',datasource);
let assetLock;try{assetLock=await readJson('data/assets-lock.json');}catch(e){throw new Error('Missing optimized images. Run npm run fetch:originals && npm run images, then npm run build.',{cause:e});}
const assets=assetLock.images.flatMap(i=>i.assets);
await writeJson('manifest.json',{package:pkg.name,version:pkg.version,emojiCount:emojis.length,imageCount:assets.length,formats:FORMATS,totalImageBytes:assets.reduce((n,a)=>n+a.bytes,0),snapshotDate:'2026-09-21',assets});
const runtime=await readFile(path.join(ROOT,'src/runtime.js'),'utf8');
const prefix=`// Generated by scripts/build.mjs. Code: MIT; data: see NOTICE.md.\nconst PACKAGE_NAME=${JSON.stringify(pkg.name)};\nconst VERSION=${JSON.stringify(pkg.version)};\nconst emojis=${JSON.stringify(emojis)};\n`;
const names='emojis,VERSION,PACKAGE_NAME,findEmoji,getEmojiPath,getEmojiUrl,getGoogleUrl,searchEmojis,tokenize';
await write('dist/index.js',prefix+runtime+`\nexport {${names}};\nexport default api;\n`);
await write('dist/index.cjs',prefix+runtime+'\nmodule.exports=api;\n');
const types=await readFile(path.join(ROOT,'src/index.d.ts'),'utf8');await write('dist/index.d.ts',types);await write('dist/index.d.cts',types);
await writeJson('dist/catalog.json',emojis);
console.log(`Built ${emojis.length} records, ${datasource.length} datasource base rows, ${assets.length} images indexed.`);
